services:
  postgres:
    image: postgres:18
    container_name: ai_language_bot_postgres
    environment:
      POSTGRES_DB: ai_language_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: ai_language_bot_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: ai_language_bot_whisper
    environment:
      ASR_MODEL: base
      ASR_ENGINE: faster_whisper
    ports:
      - '9000:9000'

volumes:
  pgdata:
  redis_data:
